apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: oss
spec:
  hard:
    requests.cpu: 250m
    requests.memory: 256Mi
    limits.cpu: 250m
    limits.memory: 256Mi
    requests.storage: 10Gi
