apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: oss
spec:
  hard:
    requests.cpu: 100m
    requests.memory: 128Mi
    limits.cpu: 100m
    limits.memory: 128Mi
    requests.storage: 10Gi
