apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: oss
spec:
  hard:
    requests.cpu: 4000m
    requests.memory: 4096Mi
    limits.cpu: 4000m
    limits.memory: 4096Mi
    requests.storage: 200Gi
