apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: oss
spec:
  hard:
    requests.cpu: 500m
    requests.memory: 512Mi
    limits.cpu: 500m
    limits.memory: 512Mi
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    pods: "10"
    configmaps: "10"
    secrets: "20"
    services: "10"
    services.loadbalancers: "0"
