apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: oss
spec:
  hard:
    requests.cpu: 200m
    requests.memory: 256Mi
    limits.cpu: 200m
    limits.memory: 256Mi
    requests.storage: 50Gi
    persistentvolumeclaims: "10"
    pods: "10"
    configmaps: "10"
    secrets: "20"
    services: "10"
    services.loadbalancers: "0"
